version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: room-reservation-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8889:3306"
    networks:
      - my-network

  spring-boot-app:
    build: .

    ports:
      - "8888:8888"
    networks:
      - my-network
    depends_on:
      - mysql

networks:
  my-network:
    driver: bridge